server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/demo
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace